<?php

/**
 * This is the model base class for the table "github_payload_commit_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GithubPayloadCommitUser".
 *
 * Columns in table "github_payload_commit_user" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id_github_payload_commit_user
 * @property string $fk_github_payload_commit
 * @property string $fk_github_payload_user
 * @property string $role
 *
 */
abstract class BaseGithubPayloadCommitUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'github_payload_commit_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GithubPayloadCommitUser|GithubPayloadCommitUsers', $n);
	}

	public static function representingColumn() {
		return 'role';
	}

	public function rules() {
		return array(
			array('fk_github_payload_commit, fk_github_payload_user', 'required'),
			array('fk_github_payload_commit, fk_github_payload_user', 'length', 'max'=>11),
			array('role', 'length', 'max'=>9),
			array('role', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_github_payload_commit_user, fk_github_payload_commit, fk_github_payload_user, role', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_github_payload_commit_user' => Yii::t('app', 'Id Github Payload Commit User'),
			'fk_github_payload_commit' => Yii::t('app', 'Fk Github Payload Commit'),
			'fk_github_payload_user' => Yii::t('app', 'Fk Github Payload User'),
			'role' => Yii::t('app', 'Role'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_github_payload_commit_user', $this->id_github_payload_commit_user, true);
		$criteria->compare('fk_github_payload_commit', $this->fk_github_payload_commit, true);
		$criteria->compare('fk_github_payload_user', $this->fk_github_payload_user, true);
		$criteria->compare('role', $this->role, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}